from typing import Any, Callable


class _QtMeta(type):
    def __getattr__(cls, name: str) -> Any: ...


class _QtObject(metaclass=_QtMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Qt(_QtObject): ...
class QTimer(_QtObject): ...
class QObject(_QtObject): ...
class QThread(_QtObject): ...
class QSettings(_QtObject): ...


def pyqtSignal(*args: Any, **kwargs: Any) -> Any: ...
def pyqtSlot(*args: Any, **kwargs: Any) -> Callable[[Any], Any]: ...
