from typing import Any


class _QtMeta(type):
    def __getattr__(cls, name: str) -> Any: ...


class _QtObject(metaclass=_QtMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class QAction(_QtObject): ...
class QCloseEvent(_QtObject): ...
class QColor(_QtObject): ...
class QFont(_QtObject): ...
class QIcon(_QtObject): ...
class QKeySequence(_QtObject): ...
class QMouseEvent(_QtObject): ...
class QShortcut(_QtObject): ...
class QTextCharFormat(_QtObject): ...
class QTextCursor(_QtObject): ...
