from typing import Any


class _QtMeta(type):
    def __getattr__(cls, name: str) -> Any: ...


class _QtObject(metaclass=_QtMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class QNetworkAccessManager(_QtObject): ...
class QNetworkReply(_QtObject): ...
class QNetworkRequest(_QtObject): ...
