from typing import Any


class _QtMeta(type):
    def __getattr__(cls, name: str) -> Any: ...


class _QtObject(metaclass=_QtMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class QAbstractItemView(_QtObject): ...


class QWidget(_QtObject):
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def isVisible(self) -> bool: ...
    def closeEvent(self, a0: Any | None) -> None: ...
    def mousePressEvent(self, event: Any | None) -> None: ...


class QApplication(_QtObject): ...
class QCheckBox(QWidget): ...
class QComboBox(QWidget): ...


class QDialog(QWidget):
    def done(self, a0: int) -> None: ...


class QDialogButtonBox(_QtObject): ...
class QFileDialog(QWidget): ...
class QFrame(QWidget): ...
class QGridLayout(_QtObject): ...
class QGroupBox(QWidget): ...
class QHBoxLayout(_QtObject): ...
class QInputDialog(QWidget): ...
class QLabel(QWidget): ...
class QLayout(_QtObject): ...
class QLineEdit(QWidget): ...
class QListWidget(QWidget): ...


class QMainWindow(QWidget):
    def setWindowTitle(self, title: str) -> None: ...
    def setWindowIcon(self, icon: Any) -> None: ...
    def setMinimumSize(self, width: int, height: int) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def restoreGeometry(self, geometry: Any) -> bool: ...
    def restoreState(self, state: Any) -> bool: ...
    def saveGeometry(self) -> Any: ...
    def saveState(self) -> Any: ...


class QMenu(QWidget): ...
class QMenuBar(_QtObject): ...
class QMessageBox(QWidget): ...
class QProgressBar(QWidget): ...
class QPushButton(QWidget): ...
class QSizePolicy(_QtObject): ...
class QSplitter(QWidget): ...
class QSystemTrayIcon(_QtObject): ...
class QTextEdit(QWidget): ...
class QToolBar(_QtObject): ...
class QTreeWidget(QWidget): ...
class QTreeWidgetItem(_QtObject): ...
class QVBoxLayout(_QtObject): ...
