from typing import Any


class _SeleniumMeta(type):
    def __getattr__(cls, name: str) -> Any: ...


class _SeleniumObject(metaclass=_SeleniumMeta):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class By(_SeleniumObject): ...
